import { MANIFEST_BACKGROUND_COLOR, MANIFEST_THEME_COLOR } from "@/config/app";
import {
  PWA_APPLE_TOUCH_ICON,
  PWA_FAVICON_DARK,
  PWA_FAVICON_LIGHT,
  PWA_ICON_192,
  PWA_ICON_512,
  PWA_ICON_DARK_192,
  PWA_ICON_LIGHT_192,
  PWA_LOGO_SOURCE_DARK,
  PWA_LOGO_SOURCE_LIGHT,
  PWA_PRECACHED_ASSETS,
} from "@/config/pwa-assets";

export {
  PWA_APPLE_TOUCH_ICON,
  PWA_FAVICON_DARK,
  PWA_FAVICON_LIGHT,
  PWA_ICON_192,
  PWA_ICON_512,
  PWA_ICON_DARK_192,
  PWA_ICON_LIGHT_192,
  PWA_LOGO_SOURCE_DARK,
  PWA_LOGO_SOURCE_LIGHT,
  PWA_PRECACHED_ASSETS,
};

/** Android / manifest chrome. */
export const PWA_THEME_COLOR = MANIFEST_THEME_COLOR;

/** Splash screen — OS supplies tile background behind transparent logo. */
export const PWA_SPLASH_BACKGROUND_COLOR = MANIFEST_BACKGROUND_COLOR;

/** @deprecated Use PWA_LOGO_SOURCE_DARK — kept for existing imports. */
export const PWA_LOGO_SOURCE = PWA_LOGO_SOURCE_DARK;

/** Push notifications + in-app notification banner icon. */
export const PWA_NOTIFICATION_ICON = PWA_ICON_192;

/** Generated by Serwist at production build — not available in `next dev`. */
export const PWA_SERVICE_WORKER_URL = "/sw.js";

/** Keep in sync with `disable` in next.config.ts and SerwistProviderShell. */
export const PWA_SERVICE_WORKER_ENABLED = process.env.NODE_ENV === "production";

/**
 * Full-bleed wallpaper layer — sync with `.pwa-fullscreen-bleed` in globals.css.
 */
export const PWA_FULLSCREEN_BLEED = "pwa-fullscreen-bleed";

/** Dimming overlay — full-bleed on mobile; desktop may offset below safe area. */
export const PWA_WALLPAPER_MASK = "pwa-wallpaper-mask";

/**
 * Standalone PWA viewport — disables pinch/double-tap zoom (native-like).
 * Applied via bootstrap script only when installed, not in mobile browser.
 */
export const PWA_STANDALONE_VIEWPORT_CONTENT =
  "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover";
