/** AUTO-GENERATED by `npm run fintech:logos` — do not edit. */
import type { WalletInstitutionEntry } from "@/config/wallet-institutions";

export const GENERATED_BANK_INSTITUTIONS: WalletInstitutionEntry[] = [
  {
    "name": "Aladin",
    "slug": "aladin"
  },
  {
    "name": "Allo",
    "slug": "allo"
  },
  {
    "name": "Amar Bank",
    "slug": "amar-bank"
  },
  {
    "name": "ANZ",
    "slug": "anz"
  },
  {
    "name": "Bangkok Bank",
    "slug": "bangkok-bank"
  },
  {
    "name": "Bank Artha Graha Internasional",
    "slug": "bank-artha-graha-internasional"
  },
  {
    "name": "Bank Bengkulu",
    "slug": "bank-bengkulu"
  },
  {
    "name": "Bank BJB",
    "slug": "bank-bjb"
  },
  {
    "name": "Bank BJB Syariah",
    "slug": "bank-bjb-syariah"
  },
  {
    "name": "Bank BPD Aceh",
    "slug": "bank-bpd-aceh"
  },
  {
    "name": "Bank BPD Bali",
    "slug": "bank-bpd-bali"
  },
  {
    "name": "Bank BPD Banten",
    "slug": "bank-bpd-banten"
  },
  {
    "name": "Bank BPD DIY",
    "slug": "bank-bpd-diy"
  },
  {
    "name": "Bank BPD Jambi",
    "slug": "bank-bpd-jambi"
  },
  {
    "name": "Bank BPD Jateng",
    "slug": "bank-bpd-jateng"
  },
  {
    "name": "Bank BPD Jatim",
    "slug": "bank-bpd-jatim"
  },
  {
    "name": "Bank BPD Kalbar",
    "slug": "bank-bpd-kalbar"
  },
  {
    "name": "Bank BPD Kalimantan Timur",
    "slug": "bank-bpd-kalimantan-timur"
  },
  {
    "name": "Bank BPD Kalsel",
    "slug": "bank-bpd-kalsel"
  },
  {
    "name": "Bank BPD Kalteng",
    "slug": "bank-bpd-kalteng"
  },
  {
    "name": "Bank BPD Lampung",
    "slug": "bank-bpd-lampung"
  },
  {
    "name": "Bank BPD Maluku Malut",
    "slug": "bank-bpd-maluku-malut"
  },
  {
    "name": "Bank BPD NTB Syariah",
    "slug": "bank-bpd-ntb-syariah"
  },
  {
    "name": "Bank BPD NTT",
    "slug": "bank-bpd-ntt"
  },
  {
    "name": "Bank BPD Papua",
    "slug": "bank-bpd-papua"
  },
  {
    "name": "Bank BPD Riau Kepri",
    "slug": "bank-bpd-riau-kepri"
  },
  {
    "name": "Bank BPD Riau Kepri Syariah",
    "slug": "bank-bpd-riau-kepri-syariah"
  },
  {
    "name": "Bank BPD Sulselbar",
    "slug": "bank-bpd-sulselbar"
  },
  {
    "name": "Bank BPD Sulteng",
    "slug": "bank-bpd-sulteng"
  },
  {
    "name": "Bank BPD Sultra",
    "slug": "bank-bpd-sultra"
  },
  {
    "name": "Bank BPD Sulutgo",
    "slug": "bank-bpd-sulutgo"
  },
  {
    "name": "Bank BPD Sumsel Babel",
    "slug": "bank-bpd-sumsel-babel"
  },
  {
    "name": "Bank BPD Sumsel Babel (Alt-2)",
    "slug": "bank-bpd-sumsel-babel-alt-2"
  },
  {
    "name": "Bank BPD Sumut",
    "slug": "bank-bpd-sumut"
  },
  {
    "name": "Bank Bumi Artha",
    "slug": "bank-bumi-artha"
  },
  {
    "name": "Bank Capital",
    "slug": "bank-capital"
  },
  {
    "name": "Bank Ganesha",
    "slug": "bank-ganesha"
  },
  {
    "name": "Bank INA",
    "slug": "bank-ina"
  },
  {
    "name": "Bank Index Selindo",
    "slug": "bank-index-selindo"
  },
  {
    "name": "Bank Jakarta",
    "slug": "bank-jakarta"
  },
  {
    "name": "Bank Jasa Jakarta",
    "slug": "bank-jasa-jakarta"
  },
  {
    "name": "Bank Lampung",
    "slug": "bank-lampung"
  },
  {
    "name": "Bank Mas",
    "slug": "bank-mas"
  },
  {
    "name": "Bank Maspion",
    "slug": "bank-maspion"
  },
  {
    "name": "Bank Mayapada",
    "slug": "bank-mayapada"
  },
  {
    "name": "Bank Mayora",
    "slug": "bank-mayora"
  },
  {
    "name": "Bank Mestika Dharma",
    "slug": "bank-mestika-dharma"
  },
  {
    "name": "Bank Muamalat",
    "slug": "muamalat"
  },
  {
    "name": "Bank Nagari",
    "slug": "bank-nagari"
  },
  {
    "name": "Bank of America",
    "slug": "bank-of-america"
  },
  {
    "name": "Bank of China",
    "slug": "bank-of-china"
  },
  {
    "name": "Bank of India",
    "slug": "bank-of-india"
  },
  {
    "name": "Bank of India Indonesia",
    "slug": "bank-of-india-indonesia"
  },
  {
    "name": "Bank Raya",
    "slug": "bank-raya"
  },
  {
    "name": "Bank Resona Perdania",
    "slug": "bank-resona-perdania"
  },
  {
    "name": "Bank Sahabat Sampoerna",
    "slug": "bank-sahabat-sampoerna"
  },
  {
    "name": "Bank Saqu",
    "slug": "bank-saqu"
  },
  {
    "name": "Bank SMBC Indonesia",
    "slug": "bank-smbc-indonesia"
  },
  {
    "name": "Bank Victoria",
    "slug": "bank-victoria"
  },
  {
    "name": "Bank Victoria Syariah",
    "slug": "bank-victoria-syariah"
  },
  {
    "name": "Bank Woori Saudara",
    "slug": "bank-woori-saudara"
  },
  {
    "name": "BCA",
    "slug": "bca"
  },
  {
    "name": "BCA Digital",
    "slug": "bca-digital"
  },
  {
    "name": "BCA Syariah",
    "slug": "bca-syariah"
  },
  {
    "name": "blu by BCA Digital",
    "slug": "blu-bca"
  },
  {
    "name": "BNC",
    "slug": "bnc"
  },
  {
    "name": "BNI",
    "slug": "bni"
  },
  {
    "name": "BNP Paribas",
    "slug": "bnp-paribas"
  },
  {
    "name": "BRI",
    "slug": "bri"
  },
  {
    "name": "BRI (Vertical)",
    "slug": "bri-vertical"
  },
  {
    "name": "BSI",
    "slug": "bsi"
  },
  {
    "name": "BSN",
    "slug": "bsn"
  },
  {
    "name": "BTN",
    "slug": "btn"
  },
  {
    "name": "BTN Syariah",
    "slug": "btn-syariah"
  },
  {
    "name": "BTPN",
    "slug": "btpn"
  },
  {
    "name": "BTPN Syariah",
    "slug": "btpn-syariah"
  },
  {
    "name": "CCB Indonesia",
    "slug": "ccb-indonesia"
  },
  {
    "name": "CIMB Niaga",
    "slug": "cimb-niaga"
  },
  {
    "name": "CIMB Niaga Syariah",
    "slug": "cimb-niaga-syariah"
  },
  {
    "name": "Citibank",
    "slug": "citibank"
  },
  {
    "name": "Commonwealth",
    "slug": "commonwealth"
  },
  {
    "name": "Credit Suisse",
    "slug": "credit-suisse"
  },
  {
    "name": "CTBC Bank",
    "slug": "ctbc-bank"
  },
  {
    "name": "Danamon",
    "slug": "danamon"
  },
  {
    "name": "Danamon (MUFG)",
    "slug": "danamon-mufg"
  },
  {
    "name": "Danamon Syariah",
    "slug": "danamon-syariah"
  },
  {
    "name": "DBS",
    "slug": "dbs"
  },
  {
    "name": "Deutsche Bank",
    "slug": "deutsche-bank"
  },
  {
    "name": "hibank",
    "slug": "hibank"
  },
  {
    "name": "HSBC",
    "slug": "hsbc"
  },
  {
    "name": "IBK Bank",
    "slug": "ibk-bank"
  },
  {
    "name": "ICBC",
    "slug": "icbc"
  },
  {
    "name": "ING Bank",
    "slug": "ing-bank"
  },
  {
    "name": "J Trust Bank",
    "slug": "j-trust-bank"
  },
  {
    "name": "Jago",
    "slug": "jago"
  },
  {
    "name": "Jenius",
    "slug": "jenius"
  },
  {
    "name": "JP Morgan Chase",
    "slug": "jp-morgan-chase"
  },
  {
    "name": "KB Bukopin",
    "slug": "kb-bukopin"
  },
  {
    "name": "KB Bukopin Syariah",
    "slug": "kb-bukopin-syariah"
  },
  {
    "name": "KEB Hana Bank",
    "slug": "keb-hana-bank"
  },
  {
    "name": "Krom",
    "slug": "krom"
  },
  {
    "name": "LINE Bank",
    "slug": "line-bank"
  },
  {
    "name": "Mandiri",
    "slug": "mandiri"
  },
  {
    "name": "Mandiri Taspen",
    "slug": "mandiri-taspen"
  },
  {
    "name": "Maybank",
    "slug": "maybank"
  },
  {
    "name": "Mega",
    "slug": "mega"
  },
  {
    "name": "Mega Syariah",
    "slug": "mega-syariah"
  },
  {
    "name": "Mizuho Bank",
    "slug": "mizuho-bank"
  },
  {
    "name": "MNC",
    "slug": "mnc"
  },
  {
    "name": "MNC Bank",
    "slug": "mnc-bank"
  },
  {
    "name": "Motion Banking",
    "slug": "motion-banking"
  },
  {
    "name": "MUFG",
    "slug": "mufg"
  },
  {
    "name": "Nanobank Syariah",
    "slug": "nanobank-syariah"
  },
  {
    "name": "NOBU",
    "slug": "nobu"
  },
  {
    "name": "OCBC NISP",
    "slug": "ocbc-nisp"
  },
  {
    "name": "OK Bank",
    "slug": "ok-bank"
  },
  {
    "name": "Panin Dubai Syariah",
    "slug": "panin-dubai-syariah"
  },
  {
    "name": "PaninBank",
    "slug": "paninbank"
  },
  {
    "name": "Permata Bank",
    "slug": "permata"
  },
  {
    "name": "PRIMA Bank",
    "slug": "prima-bank"
  },
  {
    "name": "QNB",
    "slug": "qnb"
  },
  {
    "name": "SBI Indonesia",
    "slug": "sbi-indonesia"
  },
  {
    "name": "SeaBank",
    "slug": "seabank"
  },
  {
    "name": "Shinhan Bank",
    "slug": "shinhan-bank"
  },
  {
    "name": "Sinarmas",
    "slug": "sinarmas"
  },
  {
    "name": "Sinarmas Syariah",
    "slug": "sinarmas-syariah"
  },
  {
    "name": "Standard Chartered",
    "slug": "standard-chartered"
  },
  {
    "name": "Superbank",
    "slug": "superbank"
  },
  {
    "name": "UOB",
    "slug": "uob"
  },
  {
    "name": "Welab Bank",
    "slug": "welab-bank"
  }
];

export const GENERATED_EWALLET_INSTITUTIONS: WalletInstitutionEntry[] = [
  {
    "name": "Astra Pay",
    "slug": "astra-pay"
  },
  {
    "name": "Bluepay",
    "slug": "bluepay"
  },
  {
    "name": "DANA",
    "slug": "dana"
  },
  {
    "name": "Dipay",
    "slug": "dipay"
  },
  {
    "name": "DOKU",
    "slug": "doku"
  },
  {
    "name": "Dutamoney",
    "slug": "dutamoney"
  },
  {
    "name": "GoPay",
    "slug": "gopay"
  },
  {
    "name": "i.saku",
    "slug": "i-saku"
  },
  {
    "name": "JakOne Pay",
    "slug": "jakone-pay"
  },
  {
    "name": "Kaspro",
    "slug": "kaspro"
  },
  {
    "name": "LinkAja",
    "slug": "linkaja"
  },
  {
    "name": "Motion Pay",
    "slug": "motion-pay"
  },
  {
    "name": "Netzme",
    "slug": "netzme"
  },
  {
    "name": "OTTO Pay",
    "slug": "otto-pay"
  },
  {
    "name": "OVO",
    "slug": "ovo"
  },
  {
    "name": "Paydia",
    "slug": "paydia"
  },
  {
    "name": "Paytren",
    "slug": "paytren"
  },
  {
    "name": "Pospay",
    "slug": "pospay"
  },
  {
    "name": "Shopee Pay",
    "slug": "shopee-pay"
  },
  {
    "name": "SpeedCash",
    "slug": "speedcash"
  },
  {
    "name": "TrueMoney",
    "slug": "truemoney"
  },
  {
    "name": "Uangku",
    "slug": "uangku"
  },
  {
    "name": "Yukk",
    "slug": "yukk"
  }
];

export const GENERATED_INTERNATIONAL_INSTITUTIONS: WalletInstitutionEntry[] = [
  {
    "name": "Alipay",
    "slug": "alipay"
  },
  {
    "name": "Apple Pay",
    "slug": "apple-pay"
  },
  {
    "name": "BYOND by BSI",
    "slug": "byond-bsi"
  },
  {
    "name": "Flip",
    "slug": "flip"
  },
  {
    "name": "Google Pay",
    "slug": "google-pay"
  },
  {
    "name": "Grab Pay",
    "slug": "grab-pay"
  },
  {
    "name": "MoneyGram",
    "slug": "moneygram"
  },
  {
    "name": "Payoneer",
    "slug": "payoneer"
  },
  {
    "name": "PayPal",
    "slug": "paypal"
  },
  {
    "name": "Ria Money",
    "slug": "ria-money"
  },
  {
    "name": "Samsung Pay",
    "slug": "samsung-pay"
  },
  {
    "name": "Skrill",
    "slug": "skrill"
  },
  {
    "name": "SWIFT",
    "slug": "swift"
  },
  {
    "name": "Topremit",
    "slug": "topremit"
  },
  {
    "name": "Transfez",
    "slug": "transfez"
  },
  {
    "name": "WeChat Pay",
    "slug": "wechat-pay"
  },
  {
    "name": "Western Union",
    "slug": "western-union"
  },
  {
    "name": "Wise",
    "slug": "wise"
  }
];

export const GENERATED_FINTECH_LOGO_SLUGS: string[] = [
  "aladin",
  "allo",
  "amar-bank",
  "anz",
  "bangkok-bank",
  "bank-artha-graha-internasional",
  "bank-bengkulu",
  "bank-bjb",
  "bank-bjb-syariah",
  "bank-bpd-aceh",
  "bank-bpd-bali",
  "bank-bpd-banten",
  "bank-bpd-diy",
  "bank-bpd-jambi",
  "bank-bpd-jateng",
  "bank-bpd-jatim",
  "bank-bpd-kalbar",
  "bank-bpd-kalimantan-timur",
  "bank-bpd-kalsel",
  "bank-bpd-kalteng",
  "bank-bpd-lampung",
  "bank-bpd-maluku-malut",
  "bank-bpd-ntb-syariah",
  "bank-bpd-ntt",
  "bank-bpd-papua",
  "bank-bpd-riau-kepri",
  "bank-bpd-riau-kepri-syariah",
  "bank-bpd-sulselbar",
  "bank-bpd-sulteng",
  "bank-bpd-sultra",
  "bank-bpd-sulutgo",
  "bank-bpd-sumsel-babel",
  "bank-bpd-sumsel-babel-alt-2",
  "bank-bpd-sumut",
  "bank-bumi-artha",
  "bank-capital",
  "bank-ganesha",
  "bank-ina",
  "bank-index-selindo",
  "bank-jakarta",
  "bank-jasa-jakarta",
  "bank-lampung",
  "bank-mas",
  "bank-maspion",
  "bank-mayapada",
  "bank-mayora",
  "bank-mestika-dharma",
  "muamalat",
  "bank-nagari",
  "bank-of-america",
  "bank-of-china",
  "bank-of-india",
  "bank-of-india-indonesia",
  "bank-raya",
  "bank-resona-perdania",
  "bank-sahabat-sampoerna",
  "bank-saqu",
  "bank-smbc-indonesia",
  "bank-victoria",
  "bank-victoria-syariah",
  "bank-woori-saudara",
  "bca",
  "bca-digital",
  "bca-syariah",
  "blu-bca",
  "bnc",
  "bni",
  "bnp-paribas",
  "bri",
  "bri-vertical",
  "bsi",
  "bsn",
  "btn",
  "btn-syariah",
  "btpn",
  "btpn-syariah",
  "ccb-indonesia",
  "cimb-niaga",
  "cimb-niaga-syariah",
  "citibank",
  "commonwealth",
  "credit-suisse",
  "ctbc-bank",
  "danamon",
  "danamon-mufg",
  "danamon-syariah",
  "dbs",
  "deutsche-bank",
  "hibank",
  "hsbc",
  "ibk-bank",
  "icbc",
  "ing-bank",
  "j-trust-bank",
  "jago",
  "jenius",
  "jp-morgan-chase",
  "kb-bukopin",
  "kb-bukopin-syariah",
  "keb-hana-bank",
  "krom",
  "line-bank",
  "mandiri",
  "mandiri-taspen",
  "maybank",
  "mega",
  "mega-syariah",
  "mizuho-bank",
  "mnc",
  "mnc-bank",
  "motion-banking",
  "mufg",
  "nanobank-syariah",
  "nobu",
  "ocbc-nisp",
  "ok-bank",
  "panin-dubai-syariah",
  "paninbank",
  "permata",
  "prima-bank",
  "qnb",
  "sbi-indonesia",
  "seabank",
  "shinhan-bank",
  "sinarmas",
  "sinarmas-syariah",
  "standard-chartered",
  "superbank",
  "uob",
  "welab-bank",
  "astra-pay",
  "bluepay",
  "dana",
  "dipay",
  "doku",
  "dutamoney",
  "gopay",
  "i-saku",
  "jakone-pay",
  "kaspro",
  "linkaja",
  "motion-pay",
  "netzme",
  "otto-pay",
  "ovo",
  "paydia",
  "paytren",
  "pospay",
  "shopee-pay",
  "speedcash",
  "truemoney",
  "uangku",
  "yukk",
  "alipay",
  "apple-pay",
  "byond-bsi",
  "flip",
  "google-pay",
  "grab-pay",
  "moneygram",
  "payoneer",
  "paypal",
  "ria-money",
  "samsung-pay",
  "skrill",
  "swift",
  "topremit",
  "transfez",
  "wechat-pay",
  "western-union",
  "wise"
];
