/** AUTO-GENERATED by `npm run fintech:logos` — do not edit. */
import type { WalletInstitutionBrandColor } from "@/config/wallet-institutions";

export const GENERATED_WALLET_INSTITUTION_BRAND_COLORS: Record<
  string,
  WalletInstitutionBrandColor
> = {
  "aladin": {
    "primary": "#1B21CC",
    "secondary": "#D9D9D9"
  },
  "alipay": {
    "primary": "#1677FF"
  },
  "allo": {
    "primary": "#FFBC25",
    "secondary": "#282828"
  },
  "amar-bank": {
    "primary": "#239BD7",
    "secondary": "#92A666"
  },
  "anz": {
    "primary": "#169CD4"
  },
  "astra-pay": {
    "primary": "#0045E5",
    "secondary": "#EAE702"
  },
  "bangkok-bank": {
    "primary": "#1F4396"
  },
  "bank-artha-graha-internasional": {
    "primary": "#A28548"
  },
  "bank-bengkulu": {
    "primary": "#00923F",
    "secondary": "#DF4C18"
  },
  "bank-bjb": {
    "primary": "#1B517E"
  },
  "bank-bjb-syariah": {
    "primary": "#2B5E87",
    "secondary": "#B53838"
  },
  "bank-bpd-aceh": {
    "primary": "#72BB38",
    "secondary": "#9EC92A"
  },
  "bank-bpd-bali": {
    "primary": "#019966",
    "secondary": "#8C8101"
  },
  "bank-bpd-banten": {
    "primary": "#EC2127",
    "secondary": "#221E1F"
  },
  "bank-bpd-diy": {
    "primary": "#34368F"
  },
  "bank-bpd-jambi": {
    "primary": "#C13439",
    "secondary": "#EC9033"
  },
  "bank-bpd-jateng": {
    "primary": "#ED1C24",
    "secondary": "#FED860"
  },
  "bank-bpd-jatim": {
    "primary": "#D2272C",
    "secondary": "#332C2B"
  },
  "bank-bpd-kalbar": {
    "primary": "#009B4C",
    "secondary": "#00A2E9"
  },
  "bank-bpd-kalimantan-timur": {
    "primary": "#DAB741",
    "secondary": "#2A82C5"
  },
  "bank-bpd-kalsel": {
    "primary": "#3156A5",
    "secondary": "#00AA43"
  },
  "bank-bpd-kalteng": {
    "primary": "#FED62C",
    "secondary": "#E62129"
  },
  "bank-bpd-lampung": {
    "primary": "#F6D300",
    "secondary": "#3D107A"
  },
  "bank-bpd-maluku-malut": {
    "primary": "#37489C",
    "secondary": "#E76A39"
  },
  "bank-bpd-ntb-syariah": {
    "primary": "#F0B300",
    "secondary": "#00ABE6"
  },
  "bank-bpd-ntt": {
    "primary": "#72706F",
    "secondary": "#28166F"
  },
  "bank-bpd-papua": {
    "primary": "#115588",
    "secondary": "#FECC1A"
  },
  "bank-bpd-riau-kepri": {
    "primary": "#1C1C1A",
    "secondary": "#F6A500"
  },
  "bank-bpd-riau-kepri-syariah": {
    "primary": "#FAA61A",
    "secondary": "#2A9C46"
  },
  "bank-bpd-sulselbar": {
    "primary": "#99BE3D",
    "secondary": "#173766"
  },
  "bank-bpd-sulteng": {
    "primary": "#095491",
    "secondary": "#0383B0"
  },
  "bank-bpd-sultra": {
    "primary": "#001244",
    "secondary": "#C58E10"
  },
  "bank-bpd-sulutgo": {
    "primary": "#014C8F",
    "secondary": "#ED1C24"
  },
  "bank-bpd-sumsel-babel": {
    "primary": "#4198FF",
    "secondary": "#ED1C24"
  },
  "bank-bpd-sumsel-babel-alt-2": {
    "primary": "#0077B3"
  },
  "bank-bpd-sumut": {
    "primary": "#224192",
    "secondary": "#F08519"
  },
  "bank-bumi-artha": {
    "primary": "#234089"
  },
  "bank-capital": {
    "primary": "#003058",
    "secondary": "#C72127"
  },
  "bank-ganesha": {
    "primary": "#6F6F6E"
  },
  "bank-ina": {
    "primary": "#292567",
    "secondary": "#C9252C"
  },
  "bank-index-selindo": {
    "primary": "#006EB4",
    "secondary": "#003C5D"
  },
  "bank-jakarta": {
    "primary": "#FF3E17",
    "secondary": "#020000"
  },
  "bank-lampung": {
    "primary": "#28317D",
    "secondary": "#E62530"
  },
  "bank-mas": {
    "primary": "#ED3338",
    "secondary": "#383336"
  },
  "bank-maspion": {
    "primary": "#ED1C24"
  },
  "bank-mayapada": {
    "primary": "#19335D"
  },
  "bank-mayora": {
    "primary": "#FF1C25"
  },
  "bank-mestika-dharma": {
    "primary": "#282D68"
  },
  "bank-nagari": {
    "primary": "#6579B3",
    "secondary": "#332C2B"
  },
  "bank-of-america": {
    "primary": "#0067B1",
    "secondary": "#EE2A24"
  },
  "bank-of-china": {
    "primary": "#B30738",
    "secondary": "#231F20"
  },
  "bank-of-india": {
    "primary": "#0075BF",
    "secondary": "#E53312"
  },
  "bank-of-india-indonesia": {
    "primary": "#007CC5",
    "secondary": "#191917"
  },
  "bank-raya": {
    "primary": "#FF6400",
    "secondary": "#00559F"
  },
  "bank-resona-perdania": {
    "primary": "#009E5E",
    "secondary": "#F7922A"
  },
  "bank-saqu": {
    "primary": "#1751EC"
  },
  "bank-smbc-indonesia": {
    "primary": "#134939",
    "secondary": "#C3D451"
  },
  "bank-victoria-syariah": {
    "primary": "#DD4140",
    "secondary": "#171717"
  },
  "bank-woori-saudara": {
    "primary": "#0068AC",
    "secondary": "#1283C6"
  },
  "bca": {
    "primary": "#0060AF"
  },
  "bca-digital": {
    "primary": "#0060AF",
    "secondary": "#00A6B5"
  },
  "bca-syariah": {
    "primary": "#0060AF",
    "secondary": "#00A6B5"
  },
  "blu-bca": {
    "primary": "#33CDCF"
  },
  "bluepay": {
    "primary": "#2093FD",
    "secondary": "#1B49A9"
  },
  "bnc": {
    "primary": "#020202",
    "secondary": "#FFBE00"
  },
  "bni": {
    "primary": "#F15A23",
    "secondary": "#005E6A"
  },
  "bnp-paribas": {
    "primary": "#231F20",
    "secondary": "#009A7B"
  },
  "bri": {
    "primary": "#0857C3"
  },
  "bri-vertical": {
    "primary": "#00529C"
  },
  "bsi": {
    "primary": "#00A39D",
    "secondary": "#F8AD3C"
  },
  "bsn": {
    "primary": "#006747"
  },
  "btn": {
    "primary": "#015BFD"
  },
  "btn-syariah": {
    "primary": "#AD8F6B",
    "secondary": "#015BFD"
  },
  "btpn": {
    "primary": "#F58220",
    "secondary": "#7D6B56"
  },
  "btpn-syariah": {
    "primary": "#7C6A55",
    "secondary": "#F58220"
  },
  "byond-bsi": {
    "primary": "#00A39E",
    "secondary": "#FAAD3E"
  },
  "ccb-indonesia": {
    "primary": "#0066B1"
  },
  "cimb-niaga": {
    "primary": "#790008",
    "secondary": "#ED3024"
  },
  "cimb-niaga-syariah": {
    "primary": "#6A1F1D",
    "secondary": "#DA242A"
  },
  "citibank": {
    "primary": "#1C4882",
    "secondary": "#CC2131"
  },
  "credit-suisse": {
    "primary": "#183964"
  },
  "ctbc-bank": {
    "primary": "#E30512",
    "secondary": "#E30F14"
  },
  "dana": {
    "primary": "#008CEB"
  },
  "danamon": {
    "primary": "#046148",
    "secondary": "#EF9826"
  },
  "danamon-mufg": {
    "primary": "#F05A22",
    "secondary": "#FDBC38"
  },
  "danamon-syariah": {
    "primary": "#046148",
    "secondary": "#EF9826"
  },
  "dbs": {
    "primary": "#EB1B23"
  },
  "deutsche-bank": {
    "primary": "#0018A8"
  },
  "dipay": {
    "primary": "#0079FA",
    "secondary": "#010101"
  },
  "doku": {
    "primary": "#E2261D"
  },
  "dutamoney": {
    "primary": "#6E6E6E",
    "secondary": "#009CFE"
  },
  "flip": {
    "primary": "#FD6542"
  },
  "google-pay": {
    "primary": "#5F6368",
    "secondary": "#4285F4"
  },
  "gopay": {
    "primary": "#00AED6"
  },
  "grab-pay": {
    "primary": "#00B041"
  },
  "hibank": {
    "primary": "#5A5A5C",
    "secondary": "#036A80"
  },
  "hsbc": {
    "primary": "#DB0011"
  },
  "ibk-bank": {
    "primary": "#0099DA",
    "secondary": "#F15C21"
  },
  "icbc": {
    "primary": "#B2292E",
    "secondary": "#161519"
  },
  "ing-bank": {
    "primary": "#091C5A",
    "secondary": "#FF6600"
  },
  "j-trust-bank": {
    "primary": "#009EE3"
  },
  "jago": {
    "primary": "#FDAF27"
  },
  "jenius": {
    "primary": "#00A4DE"
  },
  "kaspro": {
    "primary": "#961A8B"
  },
  "kb-bukopin": {
    "primary": "#FCAF16",
    "secondary": "#776C61"
  },
  "kb-bukopin-syariah": {
    "primary": "#FBB01D",
    "secondary": "#796E63"
  },
  "keb-hana-bank": {
    "primary": "#008A8B",
    "secondary": "#E50045"
  },
  "krom": {
    "primary": "#6936D3"
  },
  "line-bank": {
    "primary": "#00D200",
    "secondary": "#008BEC"
  },
  "linkaja": {
    "primary": "#E82529"
  },
  "mandiri": {
    "primary": "#003A70"
  },
  "mandiri-taspen": {
    "primary": "#092139",
    "secondary": "#053364"
  },
  "maybank": {
    "primary": "#231F20",
    "secondary": "#FFC600"
  },
  "mega": {
    "primary": "#FFCA08",
    "secondary": "#FA9D1C"
  },
  "mega-syariah": {
    "primary": "#FFCA08",
    "secondary": "#FA9D1C"
  },
  "mizuho-bank": {
    "primary": "#183181",
    "secondary": "#ED1A3A"
  },
  "mnc": {
    "primary": "#223C77",
    "secondary": "#FFD200"
  },
  "moneygram": {
    "primary": "#DF2127"
  },
  "motion-banking": {
    "primary": "#122448",
    "secondary": "#DCA32D"
  },
  "muamalat": {
    "primary": "#6FBD62",
    "secondary": "#420655"
  },
  "mufg": {
    "primary": "#5A5A5A",
    "secondary": "#E60000"
  },
  "nanobank-syariah": {
    "primary": "#002657",
    "secondary": "#31F000"
  },
  "netzme": {
    "primary": "#009AD9",
    "secondary": "#232323"
  },
  "nobu": {
    "primary": "#E20613"
  },
  "ocbc-nisp": {
    "primary": "#D10A10"
  },
  "ok-bank": {
    "primary": "#55474A",
    "secondary": "#FAA61A"
  },
  "otto-pay": {
    "primary": "#FFCB07",
    "secondary": "#0079C0"
  },
  "ovo": {
    "primary": "#5827D4"
  },
  "panin-dubai-syariah": {
    "primary": "#2171B5",
    "secondary": "#3B720D"
  },
  "paninbank": {
    "primary": "#007DC5",
    "secondary": "#D71920"
  },
  "payoneer": {
    "primary": "#252526"
  },
  "paytren": {
    "primary": "#FB4C0F",
    "secondary": "#2E4251"
  },
  "permata": {
    "primary": "#030303",
    "secondary": "#0064FF"
  },
  "pospay": {
    "primary": "#ED6A1D",
    "secondary": "#D24124"
  },
  "prima-bank": {
    "primary": "#0D92D2"
  },
  "qnb": {
    "primary": "#878786",
    "secondary": "#00193E"
  },
  "ria-money": {
    "primary": "#FF6100"
  },
  "samsung-pay": {
    "primary": "#1E4BC6"
  },
  "sbi-indonesia": {
    "primary": "#292075",
    "secondary": "#00B5EF"
  },
  "seabank": {
    "primary": "#EA5F00",
    "secondary": "#2673DD"
  },
  "shopee-pay": {
    "primary": "#E8451E"
  },
  "sinarmas": {
    "primary": "#ED1D24",
    "secondary": "#414042"
  },
  "sinarmas-syariah": {
    "primary": "#E30016",
    "secondary": "#3B3B3B"
  },
  "skrill": {
    "primary": "#862165"
  },
  "speedcash": {
    "primary": "#007CC2",
    "secondary": "#F8941F"
  },
  "standard-chartered": {
    "primary": "#38D200",
    "secondary": "#0473EA"
  },
  "superbank": {
    "primary": "#012A31",
    "secondary": "#AFEE01"
  },
  "swift": {
    "primary": "#333D3E"
  },
  "topremit": {
    "primary": "#2E4865"
  },
  "transfez": {
    "primary": "#EA5CA1",
    "secondary": "#132F59"
  },
  "truemoney": {
    "primary": "#ED1C24",
    "secondary": "#F58220"
  },
  "uangku": {
    "primary": "#3BB8EA"
  },
  "uob": {
    "primary": "#E1091D",
    "secondary": "#002469"
  },
  "wechat-pay": {
    "primary": "#2CAD42",
    "secondary": "#4D4D4D"
  },
  "welab-bank": {
    "primary": "#F47921",
    "secondary": "#006EB8"
  },
  "western-union": {
    "primary": "#FFDD00"
  },
  "wise": {
    "primary": "#163300"
  }
};
